
import { ScrollView, LineEdit, StandardButton } from "std-widgets.slint";

export struct ChannelData {
    title: string,
    url: string,
}

export component ChannelBox inherits Rectangle {
    height: 30px;
    background: purple;
    in property <ChannelData> channelInfo;
    TouchArea {}
        Text {
        color: white;
        text: channelInfo.title;
    }

}
export component MainWindow inherits Window {
    title: @tr("rss-frida");
    property <bool> show-new-feed-dialog: false;
    in property <[ChannelData]> channels;

    callback submit-feed(string);

    min-height: 480px;
    min-width: 640px;
    
    MenuBar {
        Menu {
            title: @tr("File");
            MenuItem {
                title: @tr("New Feed...");
                activated => {show-new-feed-dialog = true;}
            }
        }
    }

    ChannelBoxBox := Rectangle {
        x: 10px;
        width: 300px;
        background: parent.background.darker(0.05);
        
        ScrollView {
            VerticalLayout {
                for channel in root.channels:
                    ChannelBox {
                        channelInfo: channel;
                    }
            }
        }
    }

    if show-new-feed-dialog: 
        Rectangle{
            height: 120px;
            width: 300px;
            background: parent.background.darker(0.2);
            feed_url := LineEdit {
            width: 200px;
            placeholder-text: @tr("Feed URL");
        }
            HorizontalLayout {
                height: 30px;
                alignment: center;
                y: parent.height - self.height - 10px;
                x: (parent.width - self.width) / 2;
                spacing: 5px;
                StandardButton {
                    kind: ok;
                    width: 80px;
                    clicked => {submit-feed(feed_url.text); show-new-feed-dialog = false;}
                }
                StandardButton {
                    kind: cancel;
                    width: 80px;
                    clicked => {show-new-feed-dialog = false;}
                }
            }       
    }
}
